[buildPlans.IosevkaForSAPDevelopment]
family = "Iosevka for SAP Development"
spacing = "normal"
serifs = "sans"
noCvSs = false
exportGlyphNames = true

  [buildPlans.IosevkaForSAPDevelopment.variants]
  inherits = "ss12"

    [buildPlans.IosevkaForSAPDevelopment.variants.design]
    one = "no-base"
    three = "two-arcs"
    four = "semi-open-serifless"
    five = "oblique-flat-serifless"
    six = "straight-bar"
    seven = "bend-serifless-crossbar"
    eight = "two-circles"
    nine = "straight-bar"
    zero = "slashed-split"
    capital-b = "standard-bilateral-serifed"
    capital-d = "standard-serifless"
    capital-g = "toothed-serifless-hooked"
    capital-i = "serifed"
    capital-j = "serifed-both-sides"
    capital-l = "motion-serifed"
    capital-m = "hanging-serifless"
    capital-n = "standard-serifless"
    capital-q = "crossing-baseline"
    capital-s = "serifless"
    capital-z = "straight-serifed"
    a = "double-storey-serifless"
    d = "toothed-serifless"
    e = "flat-crossbar"
    f = "flat-hook-serifless-crossbar-at-x-height"
    g = "single-storey-flat-hook-earless-corner"
    i = "hooky"
    j = "serifless"
    k = "straight-serifless"
    l = "tailed-serifed"
    m = "serifless"
    n = "straight-serifless"
    p = "eared-serifless"
    q = "straight-serifless"
    r = "hookless-serifless"
    t = "flat-hook-short-neck"
    u = "toothed-serifless"
    x = "straight-serifless"
    y = "straight-serifless"
    z = "straight-serifless"
    tittle = "round"
    punctuation-dot = "round"
    tilde = "high"
    asterisk = "penta-low"
    underscore = "low"
    ascii-single-quote = "raised-comma"
    paren = "normal"
    brace = "straight"
    number-sign = "upright"
    ampersand = "upper-open"
    at = "threefold"
    percent = "rings-continuous-slash"
    bar = "natural-slope"
    pilcrow = "high"
    lig-ltgteq = "slanted"
    lig-neq = "slightly-slanted"
    lig-equal-chain = "without-notch"
    lig-hyphen-chain = "without-notch"
    lig-plus-chain = "without-notch"
    lig-double-arrow-bar = "without-notch"
    lig-single-arrow-bar = "without-notch"

  [buildPlans.IosevkaForSAPDevelopment.ligations]
  inherits = "javascript"
  enables = ["arrow-l","arrow-r","arrow-lr","eqeq","lteq","eqlt","gteq","ltgt-ne","ltgt-slash-tag","html-comment","tilde-tilde","minus-minus", "plus-plus", "hash-hash"]

[buildPlans.IosevkaForSAPDevelopment.weights.ExtraLight]
shape = 200
menu = 200
css = 200

[buildPlans.IosevkaForSAPDevelopment.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaForSAPDevelopment.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IosevkaForSAPDevelopment.widths.Condensed]
shape = 500
menu = 3
css = "condensed"

[buildPlans.IosevkaForSAPDevelopment.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.IosevkaForSAPDevelopment.widths.SemiCondensed]
shape = 548
menu = 4
css = "semi-condensed"

[buildPlans.IosevkaForSAPDevelopment.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IosevkaForSAPDevelopment.slopes.Italic]
angle = 8.7
shape = "italic"
menu = "italic"
css = "italic"

[collectPlans.IosevkaForSAPDevelopment]
from = ["IosevkaForSAPDevelopment"]